# Base service config
service.name=web3-service-agent
service.port=8081
service.agentMaxSteps=8
service.modelProvider=deepseek
service.modelName=deepseek-chat

# Model list
models.0.provider=openrouter
models.0.name=openai/gpt-4.1-mini
models.0.used=true
models.0.base_url=https://openrouter.ai/api/v1
models.0.api_key=${OPENROUTER_API_KEY}

models.1.provider=openrouter
models.1.name=google/gemini-2.5-flash
models.1.used=true
models.1.base_url=https://openrouter.ai/api/v1
models.1.api_key=${OPENROUTER_API_KEY}

models.2.provider=openrouter
models.2.name=anthropic/claude-3.5-sonnet
models.2.used=true
models.2.base_url=https://openrouter.ai/api/v1
models.2.api_key=${OPENROUTER_API_KEY}

models.3.provider=deepseek
models.3.name=deepseek-chat
models.3.used=true
models.3.base_url=https://api.deepseek.com
models.3.api_key=${DEEPSEEK_API_KEY}

models.4.provider=deepseek
models.4.name=deepseek-reasoner
models.4.used=true
models.4.base_url=https://api.deepseek.com
models.4.api_key=${DEEPSEEK_API_KEY}
